### ISSUE TITLE
This is not an image that can be manipulated

### ISSUE THREAD

**Issue by davidhellmann** [nystudio107/craft-imageoptimize#21] opened 2017-12-12 14:04 UTC
I would try the plugin but this message comes with any image. It's a local installation

![image](https://user-images.githubusercontent.com/764292/33888510-9095c846-df4d-11e7-9f03-89e1d3f68866.png)

**Comment by khalwat** [comment] 2017-12-12 23:18
@davidhellmann check your `storage/web.log` for details. My guess is something isn't set up quite right.

**Comment by khalwat** [comment] 2017-12-12 23:51
@davidhellmann Try uninstalling it, updating to the latest version (1.4.0) and then re-install it.

If that doesn't work, make sure there are no pending/stuck tasks (aka `queues`), clear out everything in your `storage/logs` folder, then edit your OptimizedImages field and click on *Save*, which will cause it to try to re-save all of your assets.

Then zip up everything in `storage/logs` and send it to me here or via Slack.

**Comment by davidhellmann** [comment] 2017-12-13 08:53
Installed the 1.4.0 (removed the older one before) and tried to save the field:
![image](https://user-images.githubusercontent.com/764292/33929857-3fca3cb4-dfeb-11e7-860d-c4b0fb312271.png)

Here the Log File. 
[logs.zip](https://github.com/nystudio107/craft3-imageoptimize/files/1554783/logs.zip)

**Comment by khalwat** [comment] 2017-12-13 11:18
So this is what I'm seeing in the logs:

```
2017-12-13 09:52:45 [::1][1][-][trace][yii\db\Transaction::rollBack] Roll back transaction
2017-12-13 09:52:45 [::1][1][-][error][yii\base\ErrorException:2] yii\base\ErrorException: fopen(/Users/davidhellmann/___DEV/_Private/craft3/___dist/storage/runtime/temp/image_125a30ea5d6eb062.63164174.jpg): failed to open stream: No such file or directory in /Users/davidhellmann/___DEV/_Private/craft3/___dist/vendor/craftcms/cms/src/services/AssetTransforms.php:1348
Stack trace:
#0 /Users/davidhellmann/___DEV/_Private/craft3/___dist/vendor/craftcms/cms/src/services/AssetTransforms.php(1348): ::fopen()
#1 /Users/davidhellmann/___DEV/_Private/craft3/___dist/vendor/craftcms/cms/src/services/AssetTransforms.php(604): craft\services\AssetTransforms->_createTransformForAsset()
#2 /Users/davidhellmann/___DEV/_Private/craft3/___dist/vendor/craftcms/cms/src/services/AssetTransforms.php(507): craft\services\AssetTransforms->_generateTransform()
#3 /Users/davidhellmann/___DEV/_Private/craft3/___dist/vendor/craftcms/cms/src/services/Assets.php(587): craft\services\AssetTransforms->ensureTransformUrlByIndexModel()
#4 /Users/davidhellmann/___DEV/_Private/craft3/___dist/vendor/nystudio107/craft3-imageoptimize/src/imagetransforms/CraftImageTransform.php(46): craft\services\Assets->getAssetUrl()
#5 /Users/davidhellmann/___DEV/_Private/craft3/___dist/vendor/nystudio107/craft3-imageoptimize/src/services/OptimizedImages.php(139): nystudio107\imageoptimize\imagetransforms\CraftImageTransform::getTransformUrl()
#6 /Users/davidhellmann/___DEV/_Private/craft3/___dist/vendor/nystudio107/craft3-imageoptimize/src/fields/OptimizedImages.php(154): nystudio107\imageoptimize\services\OptimizedImages->populateOptimizedImageModel()
#7 /Users/davidhellmann/___DEV/_Private/craft3/___dist/vendor/craftcms/cms/src/base/Element.php(1800): nystudio107\imageoptimize\fields\OptimizedImages->normalizeValue()
#8 /Users/davidhellmann/___DEV/_Private/craft3/___dist/vendor/craftcms/cms/src/base/Element.php(1474): craft\base\Element->normalizeFieldValue()
#9 /Users/davidhellmann/___DEV/_Private/craft3/___dist/vendor/craftcms/cms/src/services/Content.php(186): craft\base\Element->getFieldValue()
#10 /Users/davidhellmann/___DEV/_Private/craft3/___dist/vendor/craftcms/cms/src/services/Elements.php(473): craft\services\Content->saveContent()
#11 /Users/davidhellmann/___DEV/_Private/craft3/___dist/vendor/craftcms/cms/src/queue/jobs/ResaveElements.php(73): craft\services\Elements->saveElement()
#12 /Users/davidhellmann/___DEV/_Private/craft3/___dist/vendor/yiisoft/yii2-queue/src/Queue.php(199): craft\queue\jobs\ResaveElements->execute()
#13 /Users/davidhellmann/___DEV/_Private/craft3/___dist/vendor/yiisoft/yii2-queue/src/cli/Queue.php(74): yii\queue\Queue->handleMessage()
#14 /Users/davidhellmann/___DEV/_Private/craft3/___dist/vendor/craftcms/cms/src/queue/Queue.php(95): yii\queue\cli\Queue->handleMessage()
#15 /Users/davidhellmann/___DEV/_Private/craft3/___dist/vendor/craftcms/cms/src/queue/Queue.php(592): craft\queue\Queue->run()
#16 /Users/davidhellmann/___DEV/_Private/craft3/___dist/vendor/craftcms/cms/src/queue/Queue.php(348): craft\queue\Queue->_closeRequestAndRun()
#17 /Users/davidhellmann/___DEV/_Private/craft3/___dist/vendor/yiisoft/yii2/base/Component.php(557): craft\queue\Queue->handleResponse()
#18 /Users/davidhellmann/___DEV/_Private/craft3/___dist/vendor/yiisoft/yii2/base/Component.php(557): ::call_user_func:{/Users/davidhellmann/___DEV/_Private/craft3/___dist/vendor/yiisoft/yii2/base/Component.php:557}()
#19 /Users/davidhellmann/___DEV/_Private/craft3/___dist/vendor/yiisoft/yii2/web/Response.php(338): yii\base\Component->trigger()
#20 /Users/davidhellmann/___DEV/_Private/craft3/___dist/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Response->send()
#21 /Users/davidhellmann/___DEV/_Private/craft3/___dist/web/index.php(35): yii\base\Application->run()
#22 {main}
```

**Comment by khalwat** [comment] 2017-12-13 11:22
It's failing down inside of `AssetTransforms.php`; I have a suspicion that this might be due to your local dev setup? Potentially permissions-related?

You can also try clearing all of your caches, and rebuilding your asset index, to see if that uncovers anything.

**Comment by davidhellmann** [comment] 2017-12-13 12:10
I try it after lunch, thanks so far.

**Comment by davidhellmann** [comment] 2017-12-13 13:53
Dont work. But what permissions? I never set any permissions locally with craft. hm. But is it a Plugin Problem or a problem in general?

**Comment by khalwat** [comment] 2017-12-13 13:55
uninstall the plugin, and try to use regular Craft CMS assets and asset transforms. That'll help narrow it down.

Based on what I'm seeing in the logs, I wouldn't be surprised if Craft Asset Transforms don't work either (ie, a local config setup problem).

**Comment by davidhellmann** [comment] 2017-12-13 22:59
```
  {% set thumb = {
    mode: 'crop',
    width: 100,
    height: 100,
    quality: 75,
    position: 'top-center'
  } %}

  {% set image = entry.singleImageEntry.one() %}

  <img src="{{ image.getUrl(thumb) }}" width="{{ image.getWidth(thumb) }}" height="{{ image.getHeight(thumb) }}">
```

this works fine.
![image](https://user-images.githubusercontent.com/764292/33966717-ea4d9a76-e060-11e7-8be8-75068632e21b.png)


So, I reactivate the Plugin. When I save an Image:
![image](https://user-images.githubusercontent.com/764292/33966774-1a827ba8-e061-11e7-9bac-33fb7a9b2ae0.png)


But he create a webp Image
![image](https://user-images.githubusercontent.com/764292/33966784-2388b7da-e061-11e7-8b64-b5b3465df8cb.png)

Is there an option where I can disable webp generations?

**Comment by khalwat** [comment] 2017-12-13 23:01
So I think the problem is just that the images you're using as so small that it's refusing to create variants for them; they'd be upscaled otherwise.

You can control this behavior, as well as the generation of `.webp` files via the `config.php`

**Comment by davidhellmann** [comment] 2017-12-13 23:15
![image_01](https://user-images.githubusercontent.com/764292/33967428-c9ba1f52-e063-11e7-91d0-0fa81274cc36.jpg)

here is one of the files. size is big enough I think? but okay. I check the config.

**Comment by davidhellmann** [comment] 2017-12-13 23:25
```
<?php
/**
 * ImageOptimize plugin for Craft CMS 3.x
 *
 * Automatically optimize images after they've been transformed
 *
 * @link      https://nystudio107.com
 * @copyright Copyright (c) 2017 nystudio107
 */

/**
 * ImageOptimize config.php
 *
 * This file exists only as a template for the ImageOptimize settings.
 * It does nothing on its own.
 *
 * Don't edit this file, instead copy it to 'craft/config' as
 * 'image-optimize.php' and make your changes there to override default
 * settings.
 *
 * Once copied to 'craft/config', this file will be multi-environment aware as
 * well, so you can have different settings groups for each environment, just
 * as
 * you do for 'general.php'
 */

return [
    //  What transform method should be used for image transforms?
    'transformMethod' => 'craft',

    // Domain for the Imgix transform service
    'imgixDomain' => '',

    // API key for the Imgix transform service
    'imgixApiKey' => '',

    // Should image variant be created on Asset save (aka BeforePageLoad)
    'generateTransformsBeforePageLoad' => true,

    // Controls whether a dominant color palette should be created for image variants
    // It takes a bit of time, so if you never plan to use it, you can turn it off
    'createColorPalette' => true,

    // Controls whether SVG placeholder silhouettes should be created for image variants
    // It takes a bit of time, so if you never plan to use them, you can turn it off
    'createPlaceholderSilhouettes' => true,

    // Controls whether retina images are automatically created with reduced quality
    // as per https://www.netvlies.nl/tips-updates/design-interactie/design-interactie/retina-revolution/
    'lowerQualityRetinaImageVariants' => true,

    // Controls whether Optimized Image Variants be created that would be up-scaled
    // to be larger than the original source image
    'allowUpScaledImageVariants' => false,

    // Default image variants
    'defaultVariants'            => [
        [
            'width'          => 100,
            'useAspectRatio' => false,
            'aspectRatioX'   => 4.0,
            'aspectRatioY'   => 3.0,
            'retinaSizes'    => ['1'],
            'quality'        => 60,
            'format'         => 'jpg',
        ],
    ],

    // Active image processors
    'activeImageProcessors'      => [

    ],

    // Active image variant creators
    'activeImageVariantCreators' => [

    ],

    // Preset image processors
    'imageProcessors'            => [

    ],

    'imageVariantCreators' => [

    ],

];

```

My current config. that works!
OK, I use Mamp localy… Installed all the stuff via brew but looks like not correctly :/

**Comment by davidhellmann** [comment] 2017-12-14 13:57
No Idea what I can do. 
First, this looks good:
![image](https://user-images.githubusercontent.com/764292/33995522-91116cfc-e0de-11e7-9425-a74405e73691.png)

image-optimize.php
```
<?php
/**
 * ImageOptimize plugin for Craft CMS 3.x
 *
 * Automatically optimize images after they've been transformed
 *
 * @link      https://nystudio107.com
 * @copyright Copyright (c) 2017 nystudio107
 */

/**
 * ImageOptimize config.php
 *
 * This file exists only as a template for the ImageOptimize settings.
 * It does nothing on its own.
 *
 * Don't edit this file, instead copy it to 'craft/config' as
 * 'image-optimize.php' and make your changes there to override default
 * settings.
 *
 * Once copied to 'craft/config', this file will be multi-environment aware as
 * well, so you can have different settings groups for each environment, just
 * as
 * you do for 'general.php'
 */

return [
    '*' => [
        //  What transform method should be used for image transforms?
        'transformMethod' => 'imgix',

        // Domain for the Imgix transform service
        'imgixDomain' => 'davidhellmann.imgix.net',

        // API key for the Imgix transform service
        'imgixApiKey' => 'fH2JBvjBv4GBXxTmaYfTJNtUfez6KwKQ',

        // Should image variant be created on Asset save (aka BeforePageLoad)
        'generateTransformsBeforePageLoad' => false,

        // Controls whether a dominant color palette should be created for image variants
        // It takes a bit of time, so if you never plan to use it, you can turn it off
        'createColorPalette' => true,

        // Controls whether SVG placeholder silhouettes should be created for image variants
        // It takes a bit of time, so if you never plan to use them, you can turn it off
        'createPlaceholderSilhouettes' => true,

        // Controls whether retina images are automatically created with reduced quality
        // as per https://www.netvlies.nl/tips-updates/design-interactie/design-interactie/retina-revolution/
        'lowerQualityRetinaImageVariants' => true,

        // Controls whether Optimized Image Variants be created that would be up-scaled
        // to be larger than the original source image
        'allowUpScaledImageVariants' => false,

        // Preset image processors
        'imageProcessors' => [
            // jpeg optimizers
            'jpegoptim' => [
                'commandPath' => '/usr/bin/jpegoptim',
                'commandOptions' => '-s',
                'commandOutputFileFlag' => '',
            ],
            'mozjpeg' => [
                'commandPath' => '/usr/bin/mozjpeg',
                'commandOptions' => '-optimize -copy none',
                'commandOutputFileFlag' => '-outfile',
            ],
            'jpegtran' => [
                'commandPath' => '/usr/bin/jpegtran',
                'commandOptions' => '-optimize -copy none',
                'commandOutputFileFlag' => '',
            ],
            // png optimizers
            'optipng' => [
                'commandPath' => '/usr/bin/optipng',
                'commandOptions' => '-o3 -strip all',
                'commandOutputFileFlag' => '',
            ],
            'pngcrush' => [
                'commandPath' => '/usr/bin/pngcrush',
                'commandOptions' => '-brute -ow',
                'commandOutputFileFlag' => '',
            ],
            'pngquant' => [
                'commandPath' => '/usr/bin/pngquant',
                'commandOptions' => '--strip--skip -if-larger',
                'commandOutputFileFlag' => '',
            ],
            // svg optimizers
            'svgo' => [
                'commandPath' => '/usr/bin/svgo',
                'commandOptions' => '',
                'commandOutputFileFlag' => '',
            ],
            // gif optimizers
            'gifsicle' => [
                'commandPath' => '/usr/bin/gifsicle',
                'commandOptions' => '-O3 -k 256',
                'commandOutputFileFlag' => '',
            ],
        ],
        // Default image variants
        'defaultVariants' => [

        ],

        // Active image processors
        'activeImageProcessors'      => [
            'jpg' => [
                'jpegoptim',
            ],
            'png' => [
                'optipng',
            ],
            'svg' => [
                'svgo',
            ],
            'gif' => [
                'gifsicle',
            ],
        ],

        // Active image variant creators
        'activeImageVariantCreators' => [
            'jpg' => [
                'cwebp',
            ],
            'png' => [
                'cwebp',
            ],
            'gif' => [
                'cwebp',
            ],
        ],

        'imageVariantCreators' => [
            // webp variant creator
            'cwebp' => [
                'commandPath' => '/usr/bin/cwebp',
                'commandOptions' => '',
                'commandOutputFileFlag' => '-o',
                'commandQualityFlag' => '-q',
                'imageVariantExtension' => 'webp',
            ],
        ],
    ],

    // Staging (pre-production) environment
    'live' => [

    ],

    // Staging (pre-production) environment
    'staging' => [

    ],

    // Staging (pre-production) environment
    'local' => [
        //  What transform method should be used for image transforms?
        'transformMethod' => 'craft',

        // Preset image processors
        'imageProcessors' => [
            // jpeg optimizers
            'jpegoptim' => [
                'commandPath' => '/usr/local/bin/jpegoptim',
            ],
            'mozjpeg' => [
                'commandPath' => '/usr/local/bin/mozjpeg',
            ],
            'jpegtran' => [
                'commandPath' => '/usr/local/bin/jpegtran',
            ],
            // png optimizers
            'optipng' => [
                'commandPath' => '/usr/local/bin/optipng',
            ],
            'pngcrush' => [
                'commandPath' => '/usr/local/bin/pngcrush',
            ],
            'pngquant' => [
                'commandPath' => '/usr/local/bin/pngquant',
            ],
            // svg optimizers
            'svgo' => [
                'commandPath' => '/usr/local/bin/svgo',
            ],
            // gif optimizers
            'gifsicle' => [
                'commandPath' => '/usr/local/bin/gifsicle',
            ],
        ],

        'imageVariantCreators' => [
            // webp variant creator
            'cwebp' => [
                'commandPath' => '/usr/local/bin/cwebp',
            ],
        ],
    ],
];
```

general.php
```
<?php

/**
 * General Configuration
 *
 * All of your system's general configuration settings go in here.
 * You can see a list of the default settings in craft/app/etc/config/defaults/general.php
 */

// $_ENV constants are loaded by craft-multi-environment from .env.php via public/index.php
return array(

    // All environments
    '*' => [
        // Whether "index.php" should be visible in URLs (true, false, "auto")
        'omitScriptNameInUrls' => true,
        'usePathInfo' => true,
        'cacheDuration' => false,
        'generateTransformsBeforePageLoad' => true,
        'requireMatchingUserAgentForSession' => false,
        'userSessionDuration' => 'P1W',
        'rememberedUserSessionDuration' => 'P4W',
        'defaultWeekStartDay' => 1,
        'enableCsrfProtection' => true,
        'cpTrigger' => 'admin',
        'preventUserEnumeration' => 'true',
        'sendPoweredByHeader' => 'false',
        'defaultCpLanguage' => 'en',
        'postCpLoginRedirect' => 'entries',
        'maxUploadFileSize' => 67108864,
        'defaultSearchTermOptions' => [
            'attribute' => null,
            'exact' => false,
            'exclude' => false,
            'subLeft' => true,
            'subRight' => true,
        ],
        'securityKey' => getenv('CRAFTENV_SECURITY_KEY'),
        'usePathInfo' => true,

        'defaultTemplateExtensions' => array('html', 'twig', 'rss'),

        /*
        'siteUrl' => array(
            'de' => getenv('CRAFTENV_SITE_URL') . 'de/',
            'en' => getenv('CRAFTENV_SITE_URL') . 'en/',
        ),
        */
        'siteUrl' => getenv('CRAFTENV_SITE_URL'),
        'craftEnv' => CRAFT_ENVIRONMENT,

        // Set the environmental variables
        'custom' => array(
            'basePath' => getenv('CRAFTENV_BASE_PATH'),
            'baseUrl' => getenv('CRAFTENV_BASE_URL'),
            'craftEnv' => CRAFT_ENVIRONMENT,
            'uploadUrl' => getenv('CRAFTENV_BASE_URL') . 'uploads/',
            'uploadPath' => getenv('CRAFTENV_BASE_PATH') . 'uploads/',
            'rootUrl' => getenv('CRAFTENV_SITE_URL'),
        ),
    ],

    // Live (production) environment
    'live'  => array(
        'isSystemOn' => true,
        'devMode' => false,
        'enableTemplateCaching' => true,
        'allowAutoUpdates' => false,
        'backupOnUpdate' => false,
        // Custom site-specific config settings
        'custom' => [
        ]
    ),

    // Staging (pre-production) environment
    'staging'  => array(
        'isSystemOn' => true,
        'devMode' => true,
        'enableTemplateCaching' => true,
        'allowAutoUpdates' => false,
        'backupOnUpdate' => false,
        // Custom site-specific config settings
        'custom' => [
        ]
    ),

    // Local (development) environment
    'local'  => array(
        'isSystemOn' => true,
        'devMode' => true,
        'enableTemplateCaching' => false,
        'allowAutoUpdates' => true,
        'backupOnUpdate' => true,
        'disableDevmodeMinifying' => true,
        // Custom site-specific config settings
        'custom' => [
        ]
    ),
);
```

Twig:
```
{% set image = entry.singleImageEntry %}
        <img src="{{ image.one().pluginOptimizedImageSquare.src() }}"
             srcset="{{ image.one().pluginOptimizedImageSquare.srcset() }}"
             sizes="100vw" />
```

And this is my output:
```
<img src="//craft3.test:3000/index.php/admin/actions/assets/generate-transform?transformId=6" srcset="//craft3.test:3000/index.php/admin/actions/assets/generate-transform?transformId=6 1600w, //craft3.test:3000/index.php/admin/actions/assets/generate-transform?transformId=2 1200w, //craft3.test:3000/index.php/admin/actions/assets/generate-transform?transformId=3 2400w, //craft3.test:3000/index.php/admin/actions/assets/generate-transform?transformId=8 800w, //craft3.test:3000/index.php/admin/actions/assets/generate-transform?transformId=10 400w, //craft3.test:3000/index.php/admin/actions/assets/generate-transform?transformId=9 200w" sizes="100vw">
```

Looks like there is something wrong with a path or stuff like this.

**Comment by davidhellmann** [comment] 2017-12-14 15:15
Another Screen

![image](https://user-images.githubusercontent.com/764292/33999171-0b585b5a-e0ea-11e7-9bae-65b0647566bf.png)

**Comment by davidhellmann** [comment] 2017-12-14 15:38
Think I found the problem. Maybe you can clearify that.
I use your Multienv Config.

In my general.php:

`'craftEnv' => CRAFT_ENVIRONMENT,` this line was in the `'custom'` Block. But when I add this line direct in the `'*'` Block it works. But in your example you have it only in the custom block.

What's wrong here?

**Comment by bkmorse** [comment] 2017-12-14 19:00
Running into the same problem, copied the config as image-optimize.php (did not change the file at all) into the craft config folder. Running it on a php 7 vagrant LAMP

![screen shot 2017-12-14 at 1 22 27 pm](https://user-images.githubusercontent.com/84529/34007992-e02459ec-e0d1-11e7-94b6-ff51eaa44e40.png)

![screen shot 2017-12-14 at 1 29 05 pm](https://user-images.githubusercontent.com/84529/34008287-cc95dd0a-e0d2-11e7-8993-154eb31bf39e.png)

I have an asset volume, which uploads the image just fine using the Assets field type.

**Comment by khalwat** [comment] 2017-12-14 21:50
Sounds like you resolved the local config issue yes @davidhellmann ?

**Comment by davidhellmann** [comment] 2017-12-14 23:34
I'm not 100% sure but at the moment it looks like it works :) Thanks!

**Comment by khalwat** [comment] 2017-12-15 00:31
@bkmorse I think we got you sorted, too :)

**Comment by paraform** [comment] 2018-08-08 14:31
I'm having the same problem on my staging site with animated GIFs. 'This is not an image that can be manipulated'. I have tried moving 'craftEnv' => CRAFT_ENVIRONMENT, but it doesn't help. Just getting errors trying to convert animated GIFs.

**Comment by khalwat** [comment] 2018-08-08 20:37
@paraform perhaps you need to install ImageMagick on the server? GD (the default) doesn't support animated gifs.

**Comment by paraform** [comment] 2018-08-09 08:00
@khalwat I have Imagick 3.4.3 (ImageMagick 6.9.7-4) installed, the gif uploads and animates but it crops weirdly and won't work with image optimize.

**Comment by khalwat** [comment] 2018-08-09 08:04
I'm a little confused about how/why you'd want to make a `srcset` from `gif` files?

**Comment by paraform** [comment] 2018-08-09 09:09
I have featured images on a homepage that can be either animated gifs or images that are set sizes in a grid so need to be cropped to a ratio.

**Comment by khalwat** [comment] 2018-08-09 09:29
I'll have a look into this on my end; if you could try creating a regular Craft transform on one of these animated gifs to see what it looks like, that'd be helpful!

**Comment by paraform** [comment] 2018-08-09 16:57
A normal image transform works and the gif crops and plays. There is a weird problem when I upload the gif where it crops and distorts it, maybe there is an ImageMagick problem? I installed imagick using this recipe https://gist.github.com/jonasemde/0537c97d2c808c06493aac314284b6a2.

Here is the gif I am trying to use:

![giftest](https://user-images.githubusercontent.com/9423987/43913571-4d7042ea-9bfd-11e8-9bd8-cb5573f18b4d.gif)

And this is what is happening:

<img width="493" alt="screen shot 2018-08-09 at 17 56 59" src="https://user-images.githubusercontent.com/9423987/43913693-ac4c50d8-9bfd-11e8-8b83-4ba6c159d842.png">

Thanks.

**Comment by khalwat** [comment] 2018-08-09 20:01
Perfect, I will use this image as a test-case, thank you!

**Comment by khalwat** [comment] 2018-08-09 20:02
Do you have any image optimizers set up to be used with the `gif` file format, like `gifsicle`?

**Comment by paraform** [comment] 2018-08-09 20:04
Yeah, I have gifsicle set up.

**Comment by khalwat** [comment] 2018-08-09 20:05
Just to rule it out, try taking that out of the mix?

**Comment by khalwat** [comment] 2018-08-09 20:32
So I'm a bit confused about why a regular transform would work; ImageOptimize just uses Craft transforms under the hood. hmmmm.

**Comment by khalwat** [comment] 2018-08-09 20:52
So I've been doing a bunch of tests with your source image @paraform and I can't get it to work using regular Craft transforms either.

So I'm going to guess it's either an issue with Craft transforms and animated gifs, or an issue with Imagick and animated gifs.

I'm not sure what combination of transform mode, interlace, etc. could potentially make it work.

**Comment by paraform** [comment] 2018-08-10 10:11
@khalwat I will test different gif settings and look into imagemagick and see if I can find a solution. Installing imagemagick via imagick php doesn't seem to give you the latest version of imagemagick, I will try this https://www.enovate.co.uk/blog/2015/12/16/how-to-install-imagemagick-from-source-on-ubuntu-14.04.

**Comment by khalwat** [comment] 2018-08-10 13:38
Yeah let me know what you find out; in general, if you can get it to work with regular old Craft transforms (which should be pretty easy to test in template), then it'll work in ImageOptimize. I'm thinking there is a problem at a lower level than ImageOptimize, I'm just not sure where/what it is.

**Comment by goodmixer** [comment] 2018-08-20 09:58
I'm getting the warning "This is not an image that can be manipulated" until I set a focal point. After I set a focal point the transforms are created. Might be of help.

**Comment by khalwat** [comment] 2018-08-21 18:57
That's really strange, whether the focal point is set or not shouldn't matter (it isn't set for the majority of the images that I use)

**Comment by Gillon** [comment] 2018-08-22 15:49
@khalwat I'm encountering the same behavior as @goodmixer and not sure what has change. As only a few weeks ago we didn't need to set a focal point on an individual basis in order to get the transforms to work. This is happening with all image assets (in my case, jpgs)

**Comment by khalwat** [comment] 2018-08-22 15:51
hmmmm.  will have a look to see if this is a regression on my part, or perhaps a regress/change in Craft itself.

**Comment by Gillon** [comment] 2018-08-22 15:59
And in case this helps you in any way:

- Craft 3.0.21
- IO version 1.4.38

**Comment by khalwat** [comment] 2018-08-25 16:33
@Gillon @goodmixer so I'm attempting to reproduce this; interestingly, when I upload a new image, Image Optimize is saying the Focal Point is already set (which it shouldn't be for newly uploaded images), and the transforms work fine.

Can you give me steps to reproduce that cause this to happen for you? If I can reproduce it, I can fix it!

**Comment by khalwat** [comment] 2018-08-25 16:34
(btw, after this is solved, I will be closing this issue, because there are 3 unrelated issues in this thread)

**Comment by Gillon** [comment] 2018-08-25 17:21
@khalwat In my case, I just needed to recreate the asset volumes in order for things to work as intended. Sorry I didn't follow up sooner!

**Closed** 2018-08-25 18:44 UTC
